[build]
  base = "/"
  command = "npm run build"
  publish = "dist"


[build.environment]
  VITE_API_URL = "https://careops-backend.onrender.com/api"

# Ignore the backend folder
[ignore]
  patterns = ["backend/*"]

